### ISSUE TITLE
How to play these mods?

### ISSUE THREAD

**Issue by pikappa19** [Humming-Owl/SMG2-Mod-Builder-To-USB-Loader#6]
Hi, I have a problem I downloaded and patched this mod, but i don't know how to play that on wii, can you help me?
Thanks in advance

**Comment by Humming-Owl** [comment]
Hello. First, I want to ask some questions just to be sure how to tell you how you can play those on the Wii.

1) Is your Wii "modded"?
2) Do you have a program on your Wii that is referred to as an "USB Loader"?
3) Do you know about a program called "Wii Backup manager"?
4) Do you have an spare USB drive that is at least of 4 GB and up?

Cheers.

**Comment by pikappa19** [comment]
Yes for all question

**Comment by Humming-Owl** [comment]
Ok. Use the Wii Backup Manager program to pass the modded WBFS file into your USB drive. Plug in the USB on your Wii and then open the USB Loader and load the game. Which mod did you select?

**Comment by pikappa19** [comment]
I selected starshine and Mario Galaxy 63, but when they start the screen became green and black

**Comment by Humming-Owl** [comment]
1) From which region is your SMG2 game file (USA, JAP, PAL)?
2) Can you share an screenshot of the build process of the mod (the CMD window)? Maybe some error is displayed.
3) Which USB Loader are you using?
I will try doing it on my end just to see if it is a program error. Cheers.

**Comment by pikappa19** [comment]
I'm using a Usa wbfs version of the game, and i'm using Uloader ![IMG_20221021_190036.jpg](https://user-images.githubusercontent.com/84722283/197249793-12b2ff49-39a3-4998-aba8-aa1b68258e48.jpg)

**Comment by Humming-Owl** [comment]
Hmm. A weird error. I did the process and I could launch the game. Do you get the same screen as mine before launching the game? 

![photo_2022-10-21_13-51-07](https://user-images.githubusercontent.com/64061464/197258697-b07bbb1d-1adb-4b8b-ba46-b2c43fb224df.jpg)

Try using another USB Loader just in case like USB Loader GX or, if you can, try running the WBFS with Dolphin Emulator on your computer to see if its a valid WBFS file.

**Comment by pikappa19** [comment]
The wbfs SMG2 normal work well on dolphin, starshine start and crash, 63 work well, on wii 63 and starshine give me a black and green screen, yes the Uloader screen is the same, on USB Loader GX the 2 game give me black screen

**Comment by pikappa19** [comment]
Could you somehow send me the patched games, if only to try them out?

**Comment by Humming-Owl** [comment]
> The wbfs SMG2 normal work well on dolphin, starshine start and crash, 63 work well, on wii 63 and starshine give me a black and green screen on Uloader, yes the Uloader screen is the same, on USB Loader GX the 2 game give me black screen

Ok. It is very strange I must say, it should work. Where you got that SMG2 copy? Is it from an original disc or from somewhere else? I downloaded my copy of SMG2 from here --> https://vimm.net/vault/18172

> Could you somehow send me the patched games, if only to try them out?

I wish I could, but unfortunately my internet is very limited to do that.

Try also opening a CMD window on the same place the modded WBFS and the original WBFS are and type `dir` then press enter it should show something like this (a check on the file sizes of both the modded and the original WBFS files):

![screenshot1](https://user-images.githubusercontent.com/64061464/197281692-a58a463e-22ed-4a2b-baa1-16bfaf9eac8c.png)

**Comment by Humming-Owl** [comment]
There are also some cases similar to what you say:

https://gbatemp.net/threads/green-screen-in-smg2-since-change-wbfs-ntfs-wiiflow.241783/
https://www.reddit.com/r/WiiHacks/comments/dx22d3/how_do_i_fix_this_i_am_using_the_homebrew_channel/
https://www.youtube.com/watch?v=-xAMohDAEBE

If you have another Windows computer I would advice to try on that one as well (for patching the WBFS) and/or changing the USB drive by another one. At this point I am out of ideas on what could it be.

**Comment by pikappa19** [comment]
In the meantime thanks for your help, I downloaded the wbfs from your link, and patched with starshine once again and noticed that the size of the created wbfs file is smaller than yours, I also tried the link stuff but nothing changed , i will try as soon as i have time with a wbfs pal to see what happens, i also forward you the photo of the cmd so that you can see for yourself
![Screenshot (4)](https://user-images.githubusercontent.com/84722283/197322097-324fac3c-f2d5-4fe1-9d33-ccbfc10ddc07.png)

**Comment by pikappa19** [comment]
Ok,good news i tried with a pal iso version and 63 on Usb Loader work, now i'll try with starshine

**Comment by Humming-Owl** [comment]
Your welcome. Maybe I need to redo the patches for the USA version of the game for starshine and 63. But I am glad to know it now works for you. Have fun!

**Comment by pikappa19** [comment]
Tanks
